letmesee/models.py
from letmesee import db

class User(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(150), unique = True, nullable=False)
    password = db.Column(db.String(200), nullable = False)

letmesee/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField
from wtforms.validators import DataRequired, Length, EqualTo

class UserCreateForm(FlaskForm):
    username = StringField('사용자이름', validators=[DataRequired(), Length(min=3, max=25)])
    password1 = PasswordField('비밀번호', validators=[
        DataRequired(), EqualTo('password2', '비밀번호가 일치하지 않습니다')])
    password2 = PasswordField('비밀번호확인', validators=[DataRequired()])

class UserLoginForm(FlaskForm):
    username = StringField('사용자이름', validators=[DataRequired(), Length(min=3, max=25)])
    password = PasswordField('비밀번호', validators=[DataRequired()])

letmesee/__init__.py
"""
file : letmesee/__init__.py
"""

from flask import Flask
from flask_migrate import Migrate
from flask_sqlalchemy import SQLAlchemy
from sqlalchemy import MetaData

import config

naming_convention = {
    "ix": 'ix_%(column_0_label)s',
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(column_0_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s"
}
db = SQLAlchemy(metadata=MetaData(naming_convention=naming_convention))
migrate = Migrate()

def create_app():
    app = Flask(__name__)
    app.config.from_object(config)

    # ORM
    db.init_app(app)
    if app.config['SQLALCHEMY_DATABASE_URI'].startswith("sqlite"):
        migrate.init_app(app, db, render_as_batch=True)
    else:
        migrate.init_app(app, db)
    from . import models

    # Blue Print
    from .views import main_views, auth_views, upload_views
    app.register_blueprint(main_views.bp)
    app.register_blueprint(auth_views.bp)
    app.register_blueprint(upload_views.bp)
    
    return app

letmesee/views/auth_views.py
from flask import Blueprint, url_for, render_template, flash, request, session, g
from werkzeug.security import generate_password_hash, check_password_hash
from werkzeug.utils import redirect
import functools

from letmesee import db
from letmesee.forms import UserCreateForm, UserLoginForm
from letmesee.models import User

bp = Blueprint('auth', __name__, url_prefix='/auth')

@bp.route('/signup/', methods=('GET', 'POST'))
def signup():
    form = UserCreateForm()
    if request.method == 'POST' and form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if not user:
            user = User(username=form.username.data,
                        password=generate_password_hash(form.password1.data))
            db.session.add(user)
            db.session.commit()
            return redirect(url_for('main.index'))
        else:
            flash('이미 존재하는 사용자입니다.')
    return render_template('auth/signup.html', form=form)

def login_required(view):
    @functools.wraps(view)
    def wrapped_view(*args, **kwargs):
        if g.user is None:
            _next = request.url if request.method == 'GET' else ''
            return redirect(url_for('auth.login', next=_next))
        return view(*args, **kwargs)
    return wrapped_view

@bp.route('/login/', methods=('GET', 'POST'))
def login():
    form = UserLoginForm()
    if request.method == 'POST' and form.validate_on_submit():
        error = None
        user = User.query.filter_by(username=form.username.data).first()
        if not user:
            error = "존재하지 않는 사용자입니다."
        elif not check_password_hash(user.password, form.password.data):
            error = "비밀번호가 올바르지 않습니다."
        if error is None:
            session.clear()
            session['user_id'] = user.id
            _next = request.args.get('next', '')
            if _next:
                return redirect(_next)
            else:
                return redirect(url_for('main.index'))
        flash(error)
    return render_template('auth/login.html', form=form)

@bp.before_app_request
def load_logged_in_user():
    user_id = session.get('user_id')
    if user_id is None:
        g.user = None
    else:
        g.user = User.query.get(user_id)

@bp.route('/logout/')
def logout():
    session.clear()
    return redirect(url_for('main.index'))

letmesee/views/main_views.py
"""
file : letmesee/views/main_views.py
"""
from flask import Blueprint, render_template

bp = Blueprint('main', __name__, url_prefix='/')

@bp.route('/')
def index():
    return render_template('index.html')

letmesee/views/upload_views.py
from flask import Blueprint, render_template, request, redirect, url_for, abort, current_app, send_from_directory, g
from letmesee.views.auth_views import login_required
from flask_wtf import FlaskForm
from flask_wtf.file import FileField
from wtforms import SubmitField
from werkzeug.utils import secure_filename
import os

import pandas as pd

bp = Blueprint('upload', __name__, url_prefix='/upload')

class MyForm(FlaskForm):
    file = FileField('File')
    submit = SubmitField('Submit')

@bp.route('/')
@login_required
def index():
    return render_template('upload/index.html')

@bp.route('/', methods=['POST'])
@login_required
def upload_files():
    uploaded_file = request.files['file']
    filename = secure_filename(uploaded_file.filename)
    if filename != '':
        file_ext = os.path.splitext(filename)[1]
        if file_ext not in current_app.config['ALLOWED_EXTENSIONS']:
            abort(400)
        directory = os.path.join(current_app.config['UPLOAD_PATH'], g.user.username)
        if not os.path.exists(directory):
            os.makedirs(directory)
        uploaded_file.save(os.path.join(directory, filename))
    return redirect(url_for('upload.preview'))

@bp.route('/<filename>')
@login_required
def fetch(filename):
    directory = os.path.join('data', g.user.username)
    return send_from_directory(directory, filename)

@bp.route('/preview')
@login_required
def preview():
    try:
        directory = os.path.join(current_app.config['UPLOAD_PATH'], g.user.username)
        file = os.listdir(directory)[0]
        df = pd.read_csv(os.path.join(directory, file))
        tables = df.head(6).to_html(classes='data', header="true")
        tables = tables[:24] + '"table table-striped table-hover"' + tables[40:]
        data_info = {'df' : df,
                    'df_to_html' : [tables],
                    'num_of_rows' : df.shape[0],
                    'num_of_cols' : df.shape[1]}
    except Exception as e:
        pass
    return render_template('upload/preview.html', data_info=data_info)

letmesee/templates/base.html
<!--file name : index.html-->
<!--pwd : letmesee/templates/index.html-->

<!doctype html>
<html>
  <head>
    <!-- Required meta tags -->
    <meta charset="'utf-8">
    <meta name="description" content="누구나 쉽게 하는 무료 데이터 분석 플랫폼, 어디보자">
    <meta name="author" content="홍주영, 김승재">
    <!-- Bootstrap core CSS -->
    <link href="{{ url_for('static',filename='css/bootstrap.min.css') }}" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <title>어디보자 v1.0</title>
  </head>
  <body>
    <!-- header -->
    {% include "navbar.html" %}
    <!-- 기본 템플릿 안에 삽입될 내용 Start -->
    {% block content %}
    {% endblock %}
    <!-- 기본 템플릿 안에 삽입될 내용 End -->
  </body>
</html>

letmesee/templates/form_errors.html
<!-- 필드오류 -->
{% if form.errors %}
<div class="alert alert-danger" role="alert">
    {% for field, errors in form.errors.items() %}
    <strong>{{ form[field].label }}</strong>
    <ul>
        {% for error in errors %}
        <li>{{ error }}</li>
        {% endfor %}
    </ul>
    {% endfor %}
</div>
{% endif %}
<!-- flash 오류 -->
{% for message in get_flashed_messages() %}
<div class="alert alert-danger" role="alert">
    {{ message }}
</div>
{% endfor %}

letmesee/templates/index.html
<!--file name : index.html-->
<!--pwd : letmesee/templates/index.html-->

{% extends 'base.html' %}
{% block content %}
<!-- Main Contents -->
<div class="container py-4">
  <div class="p-5 mb-4 bg-light rounded-3">
    <div class="container-fluid py-5">
      <h1 class="display-5 fw-bold">어디보자</h1>
      <p class="col-md-8 fs-4">누구나 쉽게 하는 무료 데이터 분석 서비스, "어디보자"입니다.</p>
      <button class="btn btn-primary btn-lg" type="button">사용 방법</button>
    </div>
  </div>

  <div class="row align-items-md-stretch">
    <div class="col-md-6">
      <div class="h-100 p-5 bg-light border rounded-3">
        <h2>로그인</h2>
        <p>서비스 이용을 위해 홈페이지에 로그인합니다.</p>
        <button class="btn btn-outline-secondary" type="button" onclick="location.href='auth/login/'">시작하기</button>
      </div>
    </div>

    <div class="col-md-6">
      <div class="h-100 p-5 text-white bg-dark rounded-3">
        <h2>데이터 업로드</h2>
        <p>서비스 이용을 위해 분석에 사용할 데이터를 업로드 합니다.</p>
        <button class="btn btn-outline-light" type="button" onClick="location.href='upload'">시작하기</button>
      </div>
    </div>
  </div>
  <br>

  <div class="row align-items-md-stretch">
    <div class="col-md-6">
      <div class="h-100 p-5 text-white bg-dark rounded-3">
        <h2>데이터 요약, 시각화</h2>
        <p>통계량 요약과 그래프를 통해 데이터를 한눈에 이해할 수 있도록 합니다.</p>
        <button class="btn btn-outline-light" type="button" onClick="location.href='analysis'">시작하기</button>
      </div>
    </div>

    <div class="col-md-6">
      <div class="h-100 p-5 bg-light border rounded-3">
        <h2>통계 분석</h2>
        <p>데이터 요약에서 발견한 궁금증을 통계분석을 통해 객관적으로 해결합니다.</p>
        <button class="btn btn-outline-secondary" type="button">시작하기</button>
      </div>
    </div>
  </div>

  <!-- footer -->
  <footer class="pt-3 mt-4 text-muted border-top">
    &copy; 2022
  </footer>

</div>   
{% endblock %}

letmesee/templates/navbar.html
<!--file name : navbar.html-->
<!--pwd : letmesee/templates/navbar.html-->

<div class="container">
    <header class="d-flex flex-wrap align-items-center justify-content-center justify-content-md-between py-3 mb-4 border-bottom">
      <a href="/" class="d-flex align-items-center col-md-3 mb-2 mb-md-0 text-dark text-decoration-none">
        <img src = "{{ url_for('static',filename='icon/free-icon-analysis-809497.png') }}" width = "40" height = "32">
        <span class="fs-4">어디보자</span>
      </a>

      <ul class="nav col-12 col-md-auto mb-2 justify-content-center mb-md-0">
        <li><a href="{{ url_for('main.index') }}" class="nav-link px-2 link-secondary">Home</a></li>
        <li><a href="{{ url_for('upload.index') }}" class="nav-link px-2 link-dark">Upload</a></li>
        <li><a href="#" class="nav-link px-2 link-dark">Summarize</a></li>
        <li><a href="#" class="nav-link px-2 link-dark">Statistical Testing</a></li>
        <li><a href="#" class="nav-link px-2 link-dark">About</a></li>
      </ul>

      <div class="col-md-3 text-end">
        {% if g.user %}
        <button type="button" class="btn btn-outline-primary me-2" onclick="window.location.href='{{ url_for( 'auth.logout' ) }}';">{{g.user.username}} (Log-out)</button>
        {% else %}
        <button type="button" class="btn btn-outline-primary me-2" onclick="window.location.href='{{ url_for( 'auth.login' ) }}';">Log-in</button>
        {% endif %}
        <button type="button" class="btn btn-primary" onclick="window.location.href='{{ url_for( 'auth.signup' ) }}';">Sign-up</button>
      </div>
    </header>
  </div>

letmesee/templates/upload/index.html
{% extends 'base.html' %}
{% block content %}
<div class="container py-4">
  <h1>파일 업로드</h1>
    <form method="POST" action="" enctype="multipart/form-data">
      <p><input type="file" name="file"></p>
      <p><input type="submit" value="Submit"></p>
    </form>
    <hr>
</div>
{% endblock %}

letmesee/templates/upload/preview.html
{% extends 'base.html' %}
{% block content %}
<div class="container py-4">
  <h1>업로드 파일 미리보기</h1>
    <hr>
    <br>
    <h4> 행(Row) 개수 : {{data_info['num_of_rows']}} </h4>
    <h4> 열(Column) 개수 : {{data_info['num_of_cols']}} </h4>
    <hr>
    <br>
    {% for table in data_info['df_to_html'] %}
      {{table|safe}}
    {% endfor %}
    <br>
    <button class="btn btn-primary" type="button" onClick="location.href='/'">메인 화면</button>
    <button class="btn btn-dark" type="button" onClick="window.location.href='{{ url_for( 'upload.index' ) }}';">파일 업로드</button>
    <button class="btn btn-dark" type="button" onClick="location.href='#'">데이터 요약</button>
    <button class="btn btn-dark" type="button" onClick="location.href='#'">통계 분석</button>
</div>
{% endblock %}